[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "tts_webui_extension.xtts_simple"
version = "0.1.6"
description = "XTTS-RVC-UI is a Gradio UI for XTTSv2"
authors = [
    {name = "rsxdalv"}
]
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "coqui-tts",
]

[project.urls]
Homepage = "https://github.com/rsxdalv/tts_webui_extension.xtts_rvc_ui"

[tool.setuptools]
include-package-data = true

[tool.setuptools.packages.find]
# This will find all namespace packages automatically
namespaces = true
